# Generated by Django 3.1.3 on 2020-11-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdpm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericGroup',
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Composant', 'verbose_name_plural': 'Composants'},
        ),
        migrations.AlterModelOptions(
            name='compositiontype',
            options={'verbose_name': 'Type de de composition', 'verbose_name_plural': 'Types de compositions'},
        ),
    ]
