# Generated by Django 3.1.3 on 2020-11-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdpm', '0002_auto_20201119_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asmr',
            options={'verbose_name': 'Avis ASMR', 'verbose_name_plural': 'Avis ASMR'},
        ),
        migrations.AlterModelOptions(
            name='presentations',
            options={'verbose_name': 'Présentation', 'verbose_name_plural': 'Présentations'},
        ),
        migrations.AlterModelOptions(
            name='smr',
            options={'verbose_name': 'Avis SMR', 'verbose_name_plural': 'Avis SMR'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Spécialité', 'verbose_name_plural': 'Specialités'},
        ),
    ]
