# Generated by Django 3.1.3 on 2020-11-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdpm', '0003_auto_20201119_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentations',
            name='specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bdpm.specialty'),
            preserve_default=False,
        ),
    ]
