# Generated by Django 3.1.3 on 2020-11-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdpm', '0004_presentations_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentations',
            name='marketing_stop_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
