# Generated by Django 3.1.3 on 2020-11-23 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdpm', '0005_auto_20201123_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentrelation',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='composition_components',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='composition_quantity',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='composition_type',
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=1024)),
                ('components', models.ManyToManyField(through='bdpm.ComponentRelation', to='bdpm.Component')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bdpm.specialty')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bdpm.compositiontype')),
            ],
        ),
        migrations.AddField(
            model_name='componentrelation',
            name='composition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bdpm.composition'),
            preserve_default=False,
        ),
    ]
