# Generated by Django 3.1.3 on 2020-11-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdpm', '0006_auto_20201123_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositiontype',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
